### ISSUE TITLE
how to write a launch file to  show .xacro or .urdf file to rviz2  for ros-dashing

### ISSUE THREAD

**Issue by Amazingmum** [ros2/launch_ros#329]

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.

One additional note is that Dashing is no longer supported (and hasn't been since 2019), so you'll want to tailor your question to one of the supported distributions (Foxy, Galactic, Humble, or Rolling).
