### ISSUE TITLE
Cannot launch example

### ISSUE THREAD

**Issue by yathartha3** [ros2/launch_ros#85]
I am trying to write launch file for python package, and for some reason I am not able to build the package correctly to use with the launch file. So I tried the tutorial, and I am seeing the same issue. I don't know if I am missing something, or just doing it incorrectly.
_This might be related to build, and maybe i should open a ticket there?_

## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - source
- DDS implementation:
  - Fast-RTPS

#### Steps to reproduce issue
* Download launch_ros and build, then source
* In terminal:
```ros2 launch ros2launch ros2launch example.launch.py```
OR
```ros2 launch launch_ros pub_sub_launch.py```

#### Expected behavior
Launches example
#### Actual behavior
```
file 'example.launch.py' was not found in the share directory of package 'ros2launch' which is at '/home/yathartha/Desktop/test/install/ros2launch/share/ros2launch'
```
And similarly:
```
file 'pub_sub_launch.py' was not found in the share directory of package 'launch_ros' which is at '/home/yathartha/Desktop/test/install/launch_ros/share/launch_ros'

```

**Comment by hidmic** [comment]
@yathartha3 example launch files are currently not being installed for neither of those packages and that's intentional AFAIK. 

----

To install launch files in a pure Python package, use `data_files` to push them under `'share/' + package_name` e.g. in a `'share/' + package_name + '/launch'` subdirectory, as it is done for `demo_nodes_cpp` [here](https://github.com/ros2/demos/blob/4e3ea5d85ab93f4ebe5d8bbff6d3e86df3ab847f/demo_nodes_cpp/CMakeLists.txt#L206).
